creation_rules:
  - path_regex: deploy/k8s/testing/secret\.yaml$
    age: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
  - path_regex: deploy/k8s/staging/secret\.yaml$
    age: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
  - path_regex: deploy/k8s/production/.*secret.*\.yaml$
    age: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
  - path_regex: deploy/ci-secrets\.yaml$
    age: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
  - path_regex: deploy/woodpecker-secrets\.yaml$
    age: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
