apiVersion: ENC[AES256_GCM,data:FIs=,iv:K0owwdiMX65u68XZyBT9E8nDYR/ntT76KJt5s6Y13RU=,tag:Umb2UJmrBcBNGEinRp9nnA==,type:str]
kind: ENC[AES256_GCM,data:yLjQaVe/,iv:f+glJgRB4QFw1xs1izhoS1yOKZ/aYlhYNJ2It5hNGQs=,tag:5WDfa4CilQsrOiYGO5JIWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QrTEZ9hz9J4UD1SakaM2,iv:4R21kBAf/0DqX9d9kvs4enx2mYOJFo+phrDLEasL1Ko=,tag:/VxiYuRXmfsAJUwFXIs9lg==,type:str]
    namespace: ENC[AES256_GCM,data:i+jgFB0xi6l4/jAmqeCe,iv:k9vHc+jLT7khTW2bzPBiMgxea+HbajNrInP0qamo0nY=,tag:cgerj/xukuUKj1R2hYrQSg==,type:str]
type: ENC[AES256_GCM,data:OvqNHLpu,iv:c+k3E+Vhe6JeY4MtXQzPX37xLlwz/mH0535QtUAhiiw=,tag:lidKegtjNzVmfLx557oa8A==,type:str]
stringData:
    BUGBARN_API_KEY: ENC[AES256_GCM,data:gufesmLyi+d3oRZtjF0faCt3hQRuSYYvRqViKzmAk0okgEIpDuG0/hzE5c5nU5li,iv:ov/esQtrwKjNw1FsC8bdOJlgXZWH70BMEEb8w+fHoxw=,tag:9SMGl4S7+szRgOthETlj7g==,type:str]
    BUGBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:h2bicvQ=,iv:TJFknFWILgCF8L07FbHtOGulsq4imG+D+QBEVrB6NeM=,tag:L+29iv22YdbqCmNOIPQ+PQ==,type:str]
    BUGBARN_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:q0GIzcHNpf/amEJ4dzH7X9EKCKRQ8jFiYDhO/1gvObLBaikZDHQPhbiX3B9NYuagwPXXMT9dmQA1hQh/,iv:durQqm22RgukKfZ6GBgY/i4ewCgJzZ6kPVoXRQ0/GBI=,tag:Slalks+5HxCaJgk+EJHH1A==,type:str]
    BUGBARN_SESSION_SECRET: ENC[AES256_GCM,data:NNMBTHyA1caBEYxHo5Bzi4TngRu47RohRuhPsaCdNg==,iv:V8vUsr4JfT5Cr93eMt8lbi55uvtiSf6SvN8uDm0lgPs=,tag:nfyAstnzG9GS8UmlsvpAnA==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:5wi7AIZ4VjuGF2U5ZuQ0Pi0N,iv:Zco5XYOQ3d3X7cl3Au1puOltestyiWAj388F+NeaEBw=,tag:iTW/HeafkhErvohMRIqUXg==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:w2HCu5qcc0/jFh50PfPIBoP0+PppigOzubmwvzdDVj2gtrWtQBdPLeD6/eVhec4s,iv:bDjLJAMsv0VoOrrSsz70qffbta4kGTW0Go94HH3XjVM=,tag:t+lUOTd3fg100oHW5iLkWA==,type:str]
    OTEL_EXPORTER_OTLP_ENDPOINT: ENC[AES256_GCM,data:8FKXq8bq14C6ywtdmu+jxM6XOf6Kjyrm7EeK+c6Wkw/3Dw==,iv:l9Y/rRSeEX91AFyv3aX21KNHR9HL8YqVGsructRofhw=,tag:w9jz5Xs90ipi0GrB4jykdQ==,type:str]
    OTEL_EXPORTER_OTLP_HEADERS: ENC[AES256_GCM,data:SZiqRfZni+1Hq2cgYF8mPcqm1buqdn5UZRpWmXa6wZJM7wrUAu33sBlg3SfK2MtlbIlT7x9lVuDVvHi7dg==,iv:oF3Hbdrb8xR+7sExdqDxdab1k3J14cctR8ceiopRZbg=,tag:PyYj7blMWVgr4JhXABiu+g==,type:str]
    BUGBARN_FUNNELBARN_ENDPOINT: ENC[AES256_GCM,data:S+KiqVp6Ymt8YnajVBHmrOZYZZRofacXjxeauSWGiYhu0yHc,iv:JB6dp796AIH4Y0Ozc+K9jid3PCmEn4Z4zriEtL0mV4k=,tag:Pvdj0sWpz72fg6b/4H4lYA==,type:str]
    BUGBARN_FUNNELBARN_API_KEY: ENC[AES256_GCM,data:Fv60fthy2RwU558y7FKFY/q6JijJ02Ot4Sods4Xe3pd+ZOucIA96fw==,iv:axwYtKY3nTl4AzUymTUonT/aUykoJqxfO1XXDqV780o=,tag:69YgYpjjG4hH58BiDNcfCQ==,type:str]
    BUGBARN_OIDC_ISSUER: ENC[AES256_GCM,data:9iwFc55jUmN12n98jgTtDP8bRgj8f9QAkp7PbWc=,iv:Sff4EXUz4oMqs7peHMPFQtgReu6HF/NPcSCr6DRpp3A=,tag:hkxy5btFjSkBpEwJDMU6tQ==,type:str]
    BUGBARN_OIDC_CLIENT_ID: ENC[AES256_GCM,data:QO7zQogGZH/tCpNtw4uzagSg,iv:BOscD8WiQ0e2dzGAj/pn3dYMKHeLjA2BhPw9SAWlK44=,tag:Vvmuj3rBPGXDvS3P9+7dPw==,type:str]
    BUGBARN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:1yuEpDT5OG2zc1+RwcYCDa/zUY7u36azzUfoNOf1TiiaVYUxTdIyVfmRrw==,iv:1La8JdBwjvmrFd61aFs/JaTAAhowMVd64uVpj9HoCuw=,tag:0cW2jUWp9NbvAD75Dt7tTg==,type:str]
    BUGBARN_OIDC_REDIRECT_URL: ENC[AES256_GCM,data:P26WK8kkzKUyhrANVBsU82iiY6edePLlRXKaMS3zy+sNj6GjdqIbpVxxheFi+QKGkXsrCMrv,iv:wVoh7Ysi+Yvu3nS3O6gox5Cp4xq0+Z9N39IbyPzG1mY=,tag:2MFTvo8/7/w7o2jEJBhz7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUFJpNXlVeTBwMlJCTkRj
            NDlZcUdLVWJ1eGk4eWVyVVJyMnNtckxOY0ZVCkJ1TWlEVldmMzdIZGZxaDdRUDRs
            cmJ2K3pKR01YNWVSSDlsSzgwbGxvbFkKLS0tIEdTcXQ0UmN6L0xBdlZEY1JwUHJJ
            Lzh0WTdqSGd2Mk1QMTM4YkVoVEUxamMKDSHgxHhdSWADgqmNVJgzO7O7d4jRIGrc
            U7/75mIF3aDD3sVjQ+WuX39jEArRqfS88jiyk+arYmjblBK5rzj3hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T09:56:19Z"
    mac: ENC[AES256_GCM,data:LXnI3vz7yIIQSvYVRJ9ddEZ+bX4Adkl+gKQtok6vo2ZBlpA/t6QZnDzAZtzXCC6nWZO8YAfbgYiOdsshc/q7vS9Ztc5I1/mHs/E8PZjKMHNCtYrvQqC7kYDe1j+SwdDLBU7DLgnSp3AW+Z1X94wdiM5vtEHKw9728pxAIeohruQ=,iv:Shuu0kXVKmNXq1zR/MG33z45t6amq+pxdJpzCE7jFm4=,tag:IxgAuIPBzmWM/H7Gwf4a9w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.12.2
