apiVersion: ENC[AES256_GCM,data:KFk=,iv:p8EBg/lfktnOL6pjDvW/2Wt3n6LPqRGZ7cQu3usr/Gk=,tag:5vIKp7luj5gZFTeJ6GalUQ==,type:str]
kind: ENC[AES256_GCM,data:RXhXQVba,iv:AQMzgOcFB6XLk2O+lPh3uzP6fJea6TuB2CAgPIULc2E=,tag:ZFuuVOApKN4qbevf5ZMmFA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BwUlgEO4NGQaeMIQ++O8,iv:7g5p6rd9l9FHsRDvWCGo81oYhhl7gwpRNcqM/eHylJE=,tag:7KIFJeO8lxjKjaXuqLOhWw==,type:str]
    namespace: ENC[AES256_GCM,data:LRfo+0s/LCt/BBfy/sJd,iv:BkapxU1aDp6QN08n+JS8wthTLqTrPwz+IdraR+WykG0=,tag:loeIlaU9iVu4pf9EQDsMgg==,type:str]
type: ENC[AES256_GCM,data:AssC42pT,iv:sNSsOcG1DMS2oKIpoeXYwPClD57F+FE6IIqcnP+TJJg=,tag:xLrrH0JFZTNvlSNw7ciwng==,type:str]
stringData:
    BUGBARN_API_KEY: ENC[AES256_GCM,data:Yf+mZ8AG+OkxwlnN0QBtSLUdLsz/nx1NoKYH/w2tn0crqRcpTzYb6T1pHBw1weHw,iv:U1lITujKQ4i2S0oilETN9yvhqzyLy/+QCBPw8xSbOFM=,tag:RAi7E1QEISnf229weoNBwQ==,type:str]
    BUGBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:bzvly34=,iv:86aVB2a3jM8E5REjWUZWGCBZLkPqTOPTAhNDt9gV2NE=,tag:fOgLYh7lYwOLW3qeELP/8w==,type:str]
    BUGBARN_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:+4XM7qxfst3RHauISRVGYqGC6Lzg+L72sdfdkHDK2uODh39rQuUHZ6e/X6UgVEkZZ53JJIugTyFgtMGa,iv:DPjZbBQB9SnyyE9g3+a8XFrnZJ9JN1elZDV4oeID/xM=,tag:KfnKWmp2Fo7Y5z5O43lvkQ==,type:str]
    BUGBARN_SESSION_SECRET: ENC[AES256_GCM,data:UG51I7Aq91Qmfh8S2hh0zFfa0H+mcZN8y2G0iDsIww==,iv:ar/aJrXTuifBHCUS0PPdO0oh8k+LZtiaT2vmBCojwQM=,tag:6RWzBltCex6bt3SE3QRJJA==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:014ugqJs3CEgDSimO90OSpCI,iv:6/eiayB6xmlHYgXyhydKClMfnCaX4/GYBukz+yiYzrE=,tag:Mr4HxOrSYtwdGNHU+5gqog==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4RfA3H0JT7ud7F3d8+z4PkUdsJiB/NlBEThKa33yV9FQ5aEtaYEK40vleGdvU652,iv:31WorkpDU+klTBotbbOIV6dVXDQUAqLgnQdlPYzGOHE=,tag:suDLl3eCRQLAGLy1WziTOQ==,type:str]
sops:
    age:
        - recipient: age1gm0rxsqsmasjf36jzs96rmkw6qwadt3mcts8zpql22tsff6uf56s62vemy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHV2lGTkxseWhCaUJqN3dM
            TlE2M2ltaHNSSHJKRFhLNXVTZUdaWlBWS3pjCm0zeVFrSzdjcnpJaW96U1NuNDZx
            bXduMU9SK2I0K0xnYWxkYjlORzBrNEEKLS0tIHR1VUUxQnNIaGxCWkUzd2dhcnVy
            azNOczl2ZTNRaDA5b3FyZXZVdmh5emcKo63bClidYWHnvKjjAxzfZC7Lptmt0nN9
            sbzoWF2UOQkb/AZC/fLU9m9F42Sy/d3WBYTjb6Weti4/Bo+zgPzGYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T14:21:08Z"
    mac: ENC[AES256_GCM,data:uFDa/CWMPTWt/Oz8bPlEOw2pJGJdxh4Ca/pgnZoXPTg5z8SvMaVNqcda/+0veVaspKyYbghNyPeBtM0tkObjxejPUQZm6Vj2Rwm4yDqjHfx18/vaY3863uqEk4lrUKXwF+fvbY59pZ33clBw7lxgmkEmNFcbou/TTDNGTC6kPdk=,iv:m0Nfyyo4gqovioVrRVJt3uL3I8Jt3pQYi68cz0y4ayE=,tag:7oF11rT5Eybs17YKxIB1QQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
