apiVersion: ENC[AES256_GCM,data:4m8=,iv:WwHBh3XaMWwNDDZVsDmAbU0xJH+kdH9nBIaTR/cnRrM=,tag:7DqWfyfm7GdP4eAooQ+2BQ==,type:str]
kind: ENC[AES256_GCM,data:lVKtjH4A,iv:lR+cCH7tJdqOn0/rfgVni8nUTT3A5KNA6tYQxki235A=,tag:fJimb9G96qjuUsd4lNog7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S8Sgg/tq9e9JwVS02WQ=,iv:Wbd6P0gduLLjkHNqGKFdRS6OqT93WIKu1ZbB4jBg9o0=,tag:taRT53TkG6Yr1uje9/YXUw==,type:str]
    namespace: ENC[AES256_GCM,data:DA/JbZVD,iv:9MzuA+w3Qju71hQhyBew4IsgJO9axscWAJS6Brt9ZWU=,tag:l0q/RxrJVbvRETCinMcYWQ==,type:str]
type: ENC[AES256_GCM,data:eSC3zUkG,iv:bgv/6xCD/wrpqwYhug5kqbSlqADGJBUoeqcIJ2Xa8vM=,tag:CzHk5T6Y+bLzkllEbJjvKQ==,type:str]
stringData:
    api_key: ENC[AES256_GCM,data:7AyhqjbhCnaVpByGZ2+ViwAA2gQkro0PYjOMHq4xR1Mq1+FliOd8pwZ7aGY5c4ed+xyjTSyYXxyX4EqyiJ/k+g==,iv:XTdonHVy7igpp13ht1uL6iaOcFg/Bp2tHYYYhIyQhhE=,tag:j1ISZE1TdENov2SEACdSug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4a25vSXd1Zk5FTnJvRk1O
            ZUpsWXRJbHo5bzV2eHBYaUpNUTlQWnZzUXo4CjhucFR4RkRwb2ZxY3dhZXowSUph
            QU9Db3g1QWpGL2lzS3oyL0FsMitqYWcKLS0tIDRpaVNocUhaRUVKUFZ1UW5PNmsy
            aGg1UXprN2lNbmhmRzBsY1ZDbDBYVkUKZebrb1mmsa2zUWxdjyH0wAtvbDhjLKhQ
            dCLlixmLzh7BrH4m5c/oUUwolooXTTgz8cGbxXOgza8Wtg/CwooLTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-10-04T14:55:33Z"
    mac: ENC[AES256_GCM,data:dlBDk4lWGSeQDUjgdiSOeOmEw+I45KVkq5BQNLIdNdVIoGcJyMP+4Q/IShwHTRMjh+9qAPVy+M9nzfKUkxa0pSYBe2UHBnHLoqDY5CuMB/VDH38vzQarv8nxAXI43o8WaiB6xseXbJUyKv+gRAnSWKX6Wf2aIkFQStDAu9aizLw=,iv:RKePnWaxUyq2qsMcy2X/KRhmz6VkIOUENLyMWQvsWCA=,tag:VFjt+TPyFEQFqM6VRtAYZA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
