apiVersion: v1
kind: Service
metadata:
  name: bugbarn-redis-queue
spec:
  selector:
    app.kubernetes.io/name: bugbarn-redis-queue
    app.kubernetes.io/environment: production
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
