apiVersion: ENC[AES256_GCM,data:P4I=,iv:1bznvi+hJz8o8RDn3Nu6QgFalyR1L5OP74SHIe/35o0=,tag:fUDob1gnK0mog9se+mFN3g==,type:str]
kind: ENC[AES256_GCM,data:FLwb4af8,iv:VGdQkSCaRtBqXylre9aa/QdoZnkppS0pC79zJFv9Tvk=,tag:6jxOs2O0mOI/xBe8GBaCAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:AHJYODxsY0O+CWJxnwvm,iv:SDTqVGCgeTB1+3sYngtpmC3SdSs0hGT+2liVQ73XvjE=,tag:ijjTKCBVIXKLLNrNhgNjqA==,type:str]
    namespace: ENC[AES256_GCM,data:wGatvWQQ504fd+oBtp/Smxuq,iv:AAlHEbnSS8WjWa45jA+CQIVtfRTGm6iX/AAf3B1OS10=,tag:ovG89OObjwy549U6tc6bIw==,type:str]
type: ENC[AES256_GCM,data:NuGDWrTF,iv:edEgljWoox3ArHeZynhy0ZQLackURInUYvEw9RBN4q4=,tag:u2QTKuGuukUBK/nYCGjMDw==,type:str]
stringData:
    BUGBARN_API_KEY: ENC[AES256_GCM,data:H4nfOAUdRx6fqEYeTqKm9Ofgxo1rBietekaX4xDocpZEoSb1fzDfgQYZkuQSy9V8,iv:DumZytVlyYMlStCq2rXco5MqJUCHDQS175ogwxjwQc0=,tag:B9AHvvpGln3DRchzmzHlJw==,type:str]
    BUGBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:XWtqUO0=,iv:JOrNisCHJTyXqhmGrbWH5Algkjkcv66S/wQPdlKdlbY=,tag:93UGarNqJLRZkBZMfiVGoA==,type:str]
    BUGBARN_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:DIbbpsRN14UyxClF0eu26jchJ9Kv+UEcCLyyNjQ0N2JLjeLLYWc/nplg9OMHHkWndmRnfx6CXO7g1wT3,iv:QzKLe/SKwNDnCC3t3vhKUxVjrI8UNm69ocU1XSsdtTQ=,tag:wENTdELnUvho5HH1PQu33A==,type:str]
    BUGBARN_SESSION_SECRET: ENC[AES256_GCM,data:dEtqc2NoPmxgGNnpCNe/WwZTiHfjFm/VSWpAh8D+sA==,iv:h33hZbOoOhnIu8gSPSQVPLfWfi1yVWlaxDBdBzwlp/M=,tag:opqb1PYfHpPa6mrFN9p29g==,type:str]
    LITESTREAM_ACCESS_KEY_ID: ENC[AES256_GCM,data:6r4nwUYDFkdHUtdKTNI3rXyk,iv:ecwG9/p/+N1dh+HAjgSbwSYIEWhNUm9IqCkMHpff1Rc=,tag:4ToujH27CyPojemO+/Kx4Q==,type:str]
    LITESTREAM_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jx5RusCPiavYCUPK31J6RwXcpbPg4TriXDbCLmvULrg3UMwcytUhzI412KY8nUP7,iv:BVaz6+A2QJTZGykn718f7J3RwiIGa7vtvcAU0PYDEGM=,tag:OS6ETJa2df8UNQr9uhxBOQ==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaUN5aHZwQUlEZEd1dkN2
            WHZEWU9UR3NoZmhkYUZodXArVlU3eGRmUmhFCndOeXBRTFYwd2dEdThVTEVidUZl
            d3ZDZEFaNzduYnowNkNPc013K3ZtUHcKLS0tIGYxdWx4dnA4VmxJZ1pWWnd2SjNt
            cG1DNE4zUXBiSUFxQ21MSVovS2ZWUlkKuUXBX6IFCCLyRdF7m97DIoX31kDLC8O5
            AipFPIfigkvNphdVHCRBoE3cfVPv0Fl3cYzAB3VscdDfzwlFe0rjUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T09:54:07Z"
    mac: ENC[AES256_GCM,data:yYdbCE0n5ykfXfkNi2wV5mrl8dixkezBUtbSWDMBj3Hv+54cijMzbmGstst2OW7LkxSVOMhNMIn5kpe48o/PodIzgdCMgYyMQOh5GGhELNPJoYWBakZ/QCMUioV6/XS7BsCZu833nfLOgl0tK3mNREfRyKqtzRGeoXLn8DANI6o=,iv:O3NAzexSAhKjQtghXj5Kv+lWq1fsqY761VetNlFJsVk=,tag:GoSiU1QHIwW15q7v+KV8Iw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
