apiVersion: ENC[AES256_GCM,data:Cnc=,iv:1owCT8eQXd3jYjzjNUOZrmkNL2C5wGa1QwSjyqAWxN8=,tag:xC6XKEAScd8T5auYGwZJ9A==,type:str]
kind: ENC[AES256_GCM,data:P17mDcqg,iv:IMNyB8GTjDfXAQgGWZDnP8hNb+nBSyT2IeNAvxTFqfc=,tag:ievXoUy+r8qAsmiUMkz0yA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:gStFZfqVe6mqNkg=,iv:vfQWY5MuVDID1stwHiNDQ4r8zzA9i7OuV+pam4Sy+SY=,tag:16fv8xmtOsxwl1ASHlRE6g==,type:str]
    namespace: ENC[AES256_GCM,data:o0tKy5DKtwa1U2kZKzUHCnmk,iv:Ci5lZnHgNfpr81KeXAkPfDcZTDLpoPfA4BvGKvNWwYI=,tag:e/RZmy1QMx5xmvNodzKhhg==,type:str]
type: ENC[AES256_GCM,data:n/0Zz5Nj,iv:g+gl5YklTAf+h2HGMWcfzsjr7BCYdhqXmXaYNOkIfp8=,tag:HvCNDZwb/byyzRVB7wXHBA==,type:str]
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:ICQ+CQ1w/2wOsy+b6xo=,iv:kOZTbu9xwT9tVv4qd2D9qgRBuI71JdCpRlbr1BPNiGc=,tag:pQSOe7qVp8/MCJdDS52nWg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:bczF,iv:mCymkp60HnvsN0Pk0T7bpenanWnX1bmsq8LCHe5V2Gc=,tag:vCb6b7ucz79ER9yHbQmvug==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:IgFUVMxK2Jl1ZUihkkAT,iv:PDy9shz6sXdantsyMui0WfvOdj2yU8ox/eAfv3iXnXQ=,tag:doVQ/WKIF1+3vGzUQPTI7A==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:P9UucEeQpEU=,iv:mUosesqTck8lb+CfjgbDvXlmT5vqkW2DfM6gTgDf84c=,tag:7nhas2xAno0Q+p9NbHm2bQ==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:PyoT4Ny/DUoe/pwYQa/L,iv:zHRAivfikOJh3l4+0H6iMViQ/tp8g8rb/rsCF9VHt0Y=,tag:QF0MVQ6iMOW6mnQipgmZ2g==,type:str]
    BUGBARN_DIGEST_ENABLED: ENC[AES256_GCM,data:AaA1Qw==,iv:lfB7+cG2zRpjB6WqJHBAwSd0DNKUi1phdYbr/w05VgE=,tag:6np0gvZxvN8WYEX7TCZHyQ==,type:str]
    BUGBARN_DIGEST_TO: ENC[AES256_GCM,data:EBtaD4M8nmWWLiJqgrNB,iv:Cxn31rABll64p42vxmFvW9vyPLtlomjTli5M9LllBTg=,tag:N34wUIKfU9nf1tKUDGJyBQ==,type:str]
sops:
    age:
        - recipient: age135zcsd472vweudg2g5f7h7253tlgmq35yfy4rew332ujadm32uaq5fquy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ0dvelFlRHY0OGtzNW1C
            VWZnUjlCdy9FblFkb3JxVWhNcGRxaEZFMkZRCmZyS1RwTlI3ZlhNRGYraVdhWC9t
            VUZYOXFZbE9mK2oxM1R4NVk1V2U3N1EKLS0tIG1PYS9RZS9qODNWUlhrMDQ0bDNi
            Qm9OTzc0TGJDU2ptYjc1QU0rTHp2ck0K0uS0qXbIImKLbAcStbFCa8PWpjLwOQGB
            //UmvTsPqPQJ3mImvNzZRIcEzqk2VTF1l1IyHPcvlY3BlITZCRbEtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T02:07:39Z"
    mac: ENC[AES256_GCM,data:c3o0b/QMwKRhx36GFCGA7ujcQVilcnYmPDsmNA2J+xv/YePx4paUJsFtJGzB6mHbCKLSu4q7O9Sssrb8RluWwz/qbryR9xnzE+jrQyNmYcp0m3E6SFXuwwmoOHAzZ12SJsPVpCJEmZ2U7Qzgbjj/tz3ijXTp24siVXK1s/Dk+BM=,iv:rhrsCIQDh5NniKESVB6N0M7Dzt28FxfqL8Wn9nMPhI4=,tag:DLt2mNwsUeSb03S1k15C0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
