apiVersion: ENC[AES256_GCM,data:En4=,iv:W/Tpo2YhgLvcCh0CgfLSClx3/W6qaG1xLpfiwdWY77k=,tag:raXoON8Vn0OpkNUHGlGJ+Q==,type:str]
kind: ENC[AES256_GCM,data:DdTvUwn2,iv:v2ouMNqgb2wol+XhbGKFwdvV9RZdCJE4p+SPtPlSh1c=,tag:fSqRubQrsX5UNiZihvN9gA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SA3NUcJzgH17uIc=,iv:kArsUfBJ3DQvXnANAwML5ZLVNiEFfN16Rza3eZ780Mc=,tag:SAA/r40Hspu3b+4JGqmt5Q==,type:str]
    namespace: ENC[AES256_GCM,data:JAMr5WW0MGW0Evl4yvuSaYv9,iv:J9k7Mt8O88TB/qHORgzYJsbFMwjtlQyLsDNFuDjdGh0=,tag:by5HqGAkJ3PZdCfcu2TnYg==,type:str]
type: ENC[AES256_GCM,data:Rc3nLnn/,iv:DiEHz13UU7ovYDlDnyn45FoYAtSaiKYi70hovSXGyIA=,tag:C5LG7aWmMg6B2CPvYngs7A==,type:str]
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:e1rDMuf9jpj1Y86JT/c=,iv:xmvDBIXbggdaSUq4f3l8MRZCCGwCh876L/XiZkdwkVE=,tag:LYRlw+00nJBD1bFgJX4Ulg==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:xR5Z,iv:bHuPQgZzvPZ9EfMZTIKkScoQEBtadmw08H9hg6cSbyg=,tag:EX0GILGrLH3F4KEw71l5Ow==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:KvweQMhOopKR5/g1kVw5,iv:41pIKlb4FLc7WskZOSnYT15YhG0kIhFSWGg3L4la/bs=,tag:1DWS2wlkqZVBYf89QbmxEA==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:OKxRGuA9Ghg=,iv:de7DSd3cV2UBTGKyPmW+z9uMq5t6cfu+o3QNNaDU/KA=,tag:l3Av5CYGEuv4Yzx0hNgEpg==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:3VmGEWKjwH0muyuYW3zK,iv:PnytrYUUxxrOGjc4W7sSYEXtpQ0aQ74U/PfSsqowfSk=,tag:pq+K7e/vtrViYUmSuM4ykg==,type:str]
    BUGBARN_DIGEST_ENABLED: ENC[AES256_GCM,data:CEnuVQ==,iv:M5hnMz8euBBOmMydRIM6G6uS712FkAkVKXdhfIpXTks=,tag:66LRKTsS3IZUnEPLelycIw==,type:str]
    BUGBARN_DIGEST_TO: ENC[AES256_GCM,data:65vIDwBpGNhpzIm7spbl,iv:RZWFAoxzo/A3NefS7OaWUpz0qpZUE6tQwmMHkKKgV7c=,tag:gbxCIjik0c5a+rS8qg4/2Q==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR1NlQ2VzcXRPa1lUZnZK
            NUkyR1VsN1ZwQnhDOThXNFdXUzNzcEtWckhBCkJ3WmVhRXF5d1hqU3kvdmU2MGFv
            OWlBUWtYSjd4UlVrZzBsczlBSWVrWmMKLS0tIG85Z0xRR0d0Uml6QlRWbVE4b2wr
            OWFpMlZJcm12bE55dHpucndrVlNUdG8Kaei+D7VEFSFtTCsLNnHgbbdI0lU52pOr
            39QdUhK2Vc+xuJR2Hz/fsFW3UoCxfEYcFycJdO0rnkSsz8MQuNwEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T20:33:48Z"
    mac: ENC[AES256_GCM,data:avFbWVadVvHQTy5hA/5cOKoza7GR0MK/6uFTbCZMl4H73hcn96mq0DgcHyf50asjGT3hjO4hd6FpsytauX3Bz6lqctRYxOD6lrHxDPc1xeMFuDFvB1kgVACkyJGc/ML9jBhxNhTZP98E+YgDKAsTCiSqfZzWYiOK4K59n45+EJI=,iv:+m7yJwELG1P3two8LLSBMYtLIBNoSbFbvyY9dtXPSZs=,tag:/mHSVCNHAuAEqaDyhzTISg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
