apiVersion: ENC[AES256_GCM,data:g60=,iv:L5cHZO1aSui5o9+9DKu0N4Awz7A/Y6vOedIqpS5pu+Q=,tag:XfH8yy1jTGNFd5FFZI/y6Q==,type:str]
kind: ENC[AES256_GCM,data:koGSestq,iv:c3fTAgsqY4O+IZDX38u/IVL+MPDewFecB4zkHPYVwVU=,tag:VJO+1t3LE/uX+ur53ARnQg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:A4UVecT41LWlMLY=,iv:fD8HQirwxL7XF9QyWwv87nbO3dHazdeYNJ7qDE5rYOA=,tag:wQFGPYLA652xJZQN5yNFAg==,type:str]
    namespace: ENC[AES256_GCM,data:72NToKLsPchSQ51TA91HOiWr,iv:Bm03xQlx2bS04W3Ev1HNSarXQrSTLOgCQpKxoEuipJw=,tag:aTFVfTfDOMKkflkf3csgKA==,type:str]
type: ENC[AES256_GCM,data:5zzE3DhL,iv:6RTzYkvt4sgUxnrn9mLwV5RUF21aHfdAAomTXGxmHFA=,tag:4XKn/nPnIr1Cp3xJMVLtPg==,type:str]
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:4AXhwXy4msoAk8b+EOk=,iv:+tFbj+UI0eOyo8JI97dwYfRvML9WySkaQXzYw/TuqfU=,tag:VFtsjFke2IpyVlNzoqK6FQ==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:eGxI,iv:gzOX1Wx+ySkKqCi57pWmbPEoTBQIEb+TYDS+r7HtPSQ=,tag:VKRBRHu3CPms8GyGiRvggg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:c3nrYQbBP0TXQ+rAM1FX,iv:TYv32RLgkU1ISGLxxbh6UXwZyPcBhS91qhh3hjMsuGA=,tag:BXIRYMBCr6HcSLO1mIXdHw==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:2+xFLDJ4i/I=,iv:76I/90CZKk3D/bzKUno2Dmri5BVhNjv+sh0eVPpgHyc=,tag:TliyXCixCAv1hEff2JcqCA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:5oY/JxUZe0ERGebeGtEx,iv:lI6x/37gJE1Yb2lRUN3hd+lWXxkpF8lhc7GBQhZlZm4=,tag:vuu+oRwH4t38OcFSCKBW8A==,type:str]
    BUGBARN_DIGEST_ENABLED: ENC[AES256_GCM,data:KrnW5Q==,iv:QL1vKDhxVG1ZlYzrWWaliV+FU9scljXaAdTpcZMINJ0=,tag:J5wx1fbuhng4I5H87PWpGg==,type:str]
    BUGBARN_DIGEST_TO: ENC[AES256_GCM,data:9xJ1uWtplHXGaABpjBAg,iv:2k8cuXZblE6z0+gRIULt+x5SyIvaqhfxK+n3ND34BgM=,tag:65rhBHDKEBPZjFR4LFpfEg==,type:str]
sops:
    age:
        - recipient: age135zcsd472vweudg2g5f7h7253tlgmq35yfy4rew332ujadm32uaq5fquy9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU1ZSSnpVclkwaXhpVEh1
            UW1RQ2c4ZXBSb28xOFhPZkhIY2ZvRWlpSjFrClhxU2NHNUhpUDY3TE9wVlZWRTl4
            aDdDZ1FkUGV4VWRLbXBOeFpNVEMyM0UKLS0tIE9IYVNwUTE1dXNMeVljbE5waUk2
            dUMwSzRyU1FrdkFJVUs3TzFpOXZyNHMKPMFqjJPmQA7sZ1gEFHIC9+1DsFCWtHHB
            KBu6Xb4XJweI43lP8D7tE7AP5BdTT4gDxAsYplYilq7e+v5BEag6Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T10:09:49Z"
    mac: ENC[AES256_GCM,data:4kkT0Ub9Tr2XDJ9kayIeJs1OiDFJCpTY03C99I32g3QKw75pAdzTkuuylKfyjHjwKy/6GK27pfMMVETILY7iIcIjFvaRCnjrHtBgZ6J88wxXgiFrXk6iAY8y9YegkZ0PriLA/CHqET01NW39J6aOzrQtlBnGojX0GChlU/tJ6Mw=,iv:WA1VMj1YsCbMJZM0Y2ZjELEy2lQDi8cFXkFMXMYjYQ8=,tag:zDTE3EGa1Nnf72NpqqENWw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
