apiVersion: ENC[AES256_GCM,data:NeU=,iv:25oD7OyDLcYI526KIZP2JYamFtjQTdHq7jXuW+gkcsc=,tag:qxFtJ1IBHCjB1dwOsU4jFA==,type:str]
kind: ENC[AES256_GCM,data:E2t0//HO,iv:BKJwKRHNrjj+Nmfkp3dcV2ocnFY+PZ5Sw9evut3G88A=,tag:9BCU3iBtrIWqlsIEQCSkeQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cVywylJD0ZoCB3zANJs=,iv:ElFxagw18ROxSPA8/wmTK0qvx8C0+sxocNDHhF7Q82E=,tag:+B/fDcjo5AstuFrw19Jv6A==,type:str]
    namespace: ENC[AES256_GCM,data:svyd619v,iv:/FiD1vhzpNYGAoRnzNB//7xsyPfyXSyg3RjmVQIUNB0=,tag:6agQVhbl60A4cBInhw6rxA==,type:str]
type: ENC[AES256_GCM,data:NWftp6Qn,iv:hSGFeym42M/rURemyKiL0HyxvmooQITqRzJx0Hkr2Is=,tag:V5NmwVByKjA6yXfWfHjovw==,type:str]
stringData:
    api_key: ENC[AES256_GCM,data:rNgg0Y9PVhhhQdnCRrBh41gBhq+6C4WqVYrPxjn4zChaFLcp8KKjLz1yCAh6nd4Bi1OXBozLvZzri9QUynu5gQ==,iv:FdWfX5ft2AZNCcdddkfEyqBQTYZnpw2XMlYy2byJpBk=,tag:tpOWz/eSbkbmo3aRDnqGUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVE52cUwwY2pmTUdHcU03
            SGh0OW9qQTVNTmJIRFU4bnNadnIzSEdETlgwCk9OMkZYSDVDT1k2WnRhQVdqWnBD
            T1JPMjBSRFl4MldUNlpOeXVxa3JzSmcKLS0tIEZUUVJaRTc1TEgxZER6R0xXby9z
            bFY1aktLMVphb3RoTmdwcFMyd0N0eUEKU85BgXtsAVEJ0wEhn58jV9rDZis7d3W+
            pxpYXU45+kdKu8p6zK+KgNL+eHG7OTqRg4tuSgpWOyc9UMpMqt26JQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-10-04T14:59:26Z"
    mac: ENC[AES256_GCM,data:/L7wvMDHJi3bW110bDyhlRgAI/O1graepmNkbRM0KF7fJRteL0HvG/NVvb4OMWQ38IGdoK9Etgm1N8bvkQ0Mdfua6jlUMPNzkxwQg8zOJZ+rPTxEDGHXyyMYVK3ZBEvdwL6QR6ZXsH6BzNV3F7HQvnXfsPKZdt95Ooh9pvYw69Q=,iv:6t/+DVIVzVUa0/tRHeE5OicN9VYEqhvKJFLl4kYJFd4=,tag:ifPoN6BEIpqWhXUxGRqr2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
