#ENC[AES256_GCM,data:66NCmpN6m0LUpe3GUctMNbPdOmO8XKpgx6a4uYEUvJHE3VS1bTq1pj2N0ri++UnOY0Oev0SVaVu1YVVBew==,iv:FTeo4JcqMI0U1UTZgjBoFGjJLWGdgaerjxVPlhEx5xI=,tag:uDMw8sxShXCatb/AVlSAbQ==,type:comment]
npm:
    token: ENC[AES256_GCM,data:qfm+8J7cCBco6aq9X2vfeoCkPQoIOxP90qnVcjTTPOPJxcJl5TEEug==,iv:gopSnSwuB2iQVUgTe2FyBELW4RhUXR1+Jg9Y7ulPWqA=,tag:ZL464A5TiSNh9mACmekQbg==,type:str]
pypi:
    token: ENC[AES256_GCM,data:E3S/SCC3uKYCY9qMoMlR66BLrXeOLM0/iN2V95oz61GffmVBFpJFoRAC9v5Somxl48UOm2skfxXmArjVPBNqxFwH/EcCrRkXMn7z5vx2QkI32rnjTcjH0MWQ1wjFqjHZHJMvyU0SprFUhts+x6X7Nxjyz58/wmQmGEYaQ3F3JM6lwslhzgy7IQInKyhuMAdfljBFn80TJ2xT184S4RnXrmuiHNTgu3k9wDj06xqUd9bAdjw=,iv:PpBXkbGW6b52BtznxSO3037BPwLD7A+rYvstuZAsCq0=,tag:C/KpXesEzfxEDqBj47Nd0w==,type:str]
github:
    release_tag_pat: ENC[AES256_GCM,data:9XI/O7FwotbVpohApnQ+pCqMnVE3wqyZ6ym1UnFhfj2YPn1v6zWOkw==,iv:M5aKFIOdfolfa4PxLVVu/GxaGVX3Au5CosDEGzfkPT0=,tag:kQiDfrr+i9Y/hRwJhi5wBQ==,type:str]
r2:
    access_key: ENC[AES256_GCM,data:GfQgbURpuCe0ZhgpNVy1hEFQk/sIt74GEFp6V4YdLtQ=,iv:VEnedzmVlM8zTtInRhhNWUochpmcWCPCB2W95TO+FiI=,tag:IzCJQlOHCxUqrAJF0PR+WQ==,type:str]
    secret_key: ENC[AES256_GCM,data:fqTVj4+MyukltOzH0QpLSNx3/BXnZKfVew0Ulwvf7RgFzmr+SHZ0i4Kg/45Rl9SR4Rh67c85c1L6wtfhWLfdVQ==,iv:yDMTCHsmZsusTER7BA1HZ1tXbjXv4FlUavdhHhHkgIg=,tag:OaIHdOLhhwT3qwCYW1XptA==,type:str]
    endpoint: ENC[AES256_GCM,data:IbKqfhIl0l7Fth/lzBuB9uvD1AUs6HBSGtMau/dywWwBGAs9mXKaZquUll3yZUjM6ZLq4A0QJH5bohJDqKCXqK+4fuE=,iv:Kmfea3fJinmEJciNKVA5dIllRssUcukLgjy0fm9Sp00=,tag:+mLXkeLRUg+voTEtVFg3Gg==,type:str]
    bucket: ENC[AES256_GCM,data:kvienqlVdv/JAkJAsyj87Xd8aY7ra5OgXCd3QzMcoprrZA==,iv:jaNXmKzmXee208yPjY53PXCH8Ywi1ml7wKYdVaqp75A=,tag:wP2bbIuEQ4FpENDGdMTF1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSEY0eWdsajhFWkttLzUw
            VDVQeVEzVVhWVVRpWnlVZzlWRTl2S3VMM1NBCjcrYTRwTVM3OHJnUzNpei9BMStP
            Tjk3TVZ0RFB3N0hGZmF3amxGb1U1NTQKLS0tIE1WOENJZGhBU0RxRUVDU05SNzZI
            bUxVK01xR3VCNEEwYzBqMnVvZmE2NjQKLL9MbTRwWyp/auRXeWytQR29W/Exbi9Y
            fDXC0Ob8zoMLpzMmCdHfP4filAWuMY/COXQj1PH6MPJolw+/dliuog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-09-05T13:31:37Z"
    mac: ENC[AES256_GCM,data:06IFiguZPAtIMckfIqEahMCxt+mUWXfa66DwnKhovA8a5MX9hxHGscAicbprgWF/7YMeUk4VgZPYysHyzPrkHStM5s77MANmoN0CK3VKFMAmFKY+7fDehCvWcafIwJtRzD+zad2JDceLou76w6a4XHufKp2FEPls0km9RevQXs4=,iv:x7ztSSXyTwyV+gT3Oha8914if5/Zb07TZWUpBypRi9E=,tag:XpF16wXc606st6yElOhNiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
