#ENC[AES256_GCM,data:66NCmpN6m0LUpe3GUctMNbPdOmO8XKpgx6a4uYEUvJHE3VS1bTq1pj2N0ri++UnOY0Oev0SVaVu1YVVBew==,iv:FTeo4JcqMI0U1UTZgjBoFGjJLWGdgaerjxVPlhEx5xI=,tag:uDMw8sxShXCatb/AVlSAbQ==,type:comment]
minio:
    access_key: ENC[AES256_GCM,data:kRGFKKWK3Ic3LZPV,iv:gN6p9PKd7FSFba1FAjAm8piJoFpcWL+SAqSaqdXqqTY=,tag:ggZShF1POysYPTMfd3GgEw==,type:str]
    secret_key: ENC[AES256_GCM,data:AzRqvclgqkC4dm0v/oxdPUFxvqvlS5kz,iv:zpzf5dwzFfFU9y809mS3Sp0ChqfIcIo0Shc1fD2W4Hc=,tag:iyu5Ns91DbZtT0cC5LrIIw==,type:str]
    endpoint: ENC[AES256_GCM,data:2FjYAvO2MFnl/pTspHlQZeAtYag=,iv:5tamEupOJfdaixeXwrE4OLecfeVIROZA5sT+7lDMRPw=,tag:Z8TODDyrDVItzm74jdXljg==,type:str]
    bucket: ENC[AES256_GCM,data:POpIMJ8eCSVkCIHw57YwVGg8gJ6Yyy0=,iv:ilrYMFlKUJcXi0Rzghv8bRyZz+Yawi+/6S8VihzZv1c=,tag:6BYBhyU7A0iByJdyRNZnfQ==,type:str]
npm:
    token: ENC[AES256_GCM,data:bZKAvAQ8NgJlMBvtEWYS9vSd53V+DHYKQFpGZJ3hA0UbrGIcvh4E5A==,iv:cylKzkWGHNTiPQ54JAORiwTS7TUlBN4L/qgKZMvgEyw=,tag:JDSvNkQ0hNkfzoKkEUWrGg==,type:str]
pypi:
    token: ENC[AES256_GCM,data:E3S/SCC3uKYCY9qMoMlR66BLrXeOLM0/iN2V95oz61GffmVBFpJFoRAC9v5Somxl48UOm2skfxXmArjVPBNqxFwH/EcCrRkXMn7z5vx2QkI32rnjTcjH0MWQ1wjFqjHZHJMvyU0SprFUhts+x6X7Nxjyz58/wmQmGEYaQ3F3JM6lwslhzgy7IQInKyhuMAdfljBFn80TJ2xT184S4RnXrmuiHNTgu3k9wDj06xqUd9bAdjw=,iv:PpBXkbGW6b52BtznxSO3037BPwLD7A+rYvstuZAsCq0=,tag:C/KpXesEzfxEDqBj47Nd0w==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSEY0eWdsajhFWkttLzUw
            VDVQeVEzVVhWVVRpWnlVZzlWRTl2S3VMM1NBCjcrYTRwTVM3OHJnUzNpei9BMStP
            Tjk3TVZ0RFB3N0hGZmF3amxGb1U1NTQKLS0tIE1WOENJZGhBU0RxRUVDU05SNzZI
            bUxVK01xR3VCNEEwYzBqMnVvZmE2NjQKLL9MbTRwWyp/auRXeWytQR29W/Exbi9Y
            fDXC0Ob8zoMLpzMmCdHfP4filAWuMY/COXQj1PH6MPJolw+/dliuog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T09:09:18Z"
    mac: ENC[AES256_GCM,data:nLW1W+4ReYPpo3drPdVHQbfWW4zspSCxd+QZAZJCRc/2h0x3q+9nnOhWVQ3rHT/8kz7Ka5Nrwp9WO0kDAK8C7OXxb0C7zWZtGiStwY7uIOK2A+y7YTZFMVpPqyJOVY1A649j7ArXrYofZCzov3Wa8K7vZ4m2uSU1zRcNFd/YZUs=,iv:9sEJ0ujeO5Eq/+YQ2OrSyZb+7WIW/NcvEc5lFtjFhUg=,tag:BSN/ZOT7x3p+CDlGdYWlwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
