#ENC[AES256_GCM,data:66NCmpN6m0LUpe3GUctMNbPdOmO8XKpgx6a4uYEUvJHE3VS1bTq1pj2N0ri++UnOY0Oev0SVaVu1YVVBew==,iv:FTeo4JcqMI0U1UTZgjBoFGjJLWGdgaerjxVPlhEx5xI=,tag:uDMw8sxShXCatb/AVlSAbQ==,type:comment]
minio:
    access_key: ENC[AES256_GCM,data:kRGFKKWK3Ic3LZPV,iv:gN6p9PKd7FSFba1FAjAm8piJoFpcWL+SAqSaqdXqqTY=,tag:ggZShF1POysYPTMfd3GgEw==,type:str]
    secret_key: ENC[AES256_GCM,data:AzRqvclgqkC4dm0v/oxdPUFxvqvlS5kz,iv:zpzf5dwzFfFU9y809mS3Sp0ChqfIcIo0Shc1fD2W4Hc=,tag:iyu5Ns91DbZtT0cC5LrIIw==,type:str]
    endpoint: ENC[AES256_GCM,data:2FjYAvO2MFnl/pTspHlQZeAtYag=,iv:5tamEupOJfdaixeXwrE4OLecfeVIROZA5sT+7lDMRPw=,tag:Z8TODDyrDVItzm74jdXljg==,type:str]
    bucket: ENC[AES256_GCM,data:POpIMJ8eCSVkCIHw57YwVGg8gJ6Yyy0=,iv:ilrYMFlKUJcXi0Rzghv8bRyZz+Yawi+/6S8VihzZv1c=,tag:6BYBhyU7A0iByJdyRNZnfQ==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSEY0eWdsajhFWkttLzUw
            VDVQeVEzVVhWVVRpWnlVZzlWRTl2S3VMM1NBCjcrYTRwTVM3OHJnUzNpei9BMStP
            Tjk3TVZ0RFB3N0hGZmF3amxGb1U1NTQKLS0tIE1WOENJZGhBU0RxRUVDU05SNzZI
            bUxVK01xR3VCNEEwYzBqMnVvZmE2NjQKLL9MbTRwWyp/auRXeWytQR29W/Exbi9Y
            fDXC0Ob8zoMLpzMmCdHfP4filAWuMY/COXQj1PH6MPJolw+/dliuog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T09:22:49Z"
    mac: ENC[AES256_GCM,data:SI9AskmvAaO56MWjOzfVg8g/7qShaMtbibQ5hIdM0CIG2J9OS5udtMGlyCnuma8DUudFmT5S07tTAQ3vOy8m7yuCDKPLAfDNsOeT+qMTA8fCT1ErgubqranqepzXGTMR5ToJcY+zXaS8FxPa7QnmZ4OOFq91mppJnYgqplhjpr0=,iv:ESkttEJD9RBa+TN7ilGifrddkYUUvsVqoMjVLbuRCkE=,tag:QA5MQtdxyGbCOf7HFMxLIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
