apiVersion: ENC[AES256_GCM,data:Vog=,iv:emHcbhsCtNPYiiW3RO0ag8nmjIENx5QhkwPAYj+mK8k=,tag:hdoB03CHhnO6cMEQChsxdg==,type:str]
kind: ENC[AES256_GCM,data:WbEUsTlb,iv:SnpsfgpsM5fHx+47gbOui9/31tAqKcoFJfsYGYT8DSM=,tag:oHayVaRteoX3j+bI78Q5jg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SSFapQqCYPeTryPJl8Cw,iv:KbFBp2pVvJDfGxMWiTF9V8bZOyWVLk0xFKj6HcMroUQ=,tag:hiVj8FNv0xSjO+WUkEP/Bg==,type:str]
    namespace: ENC[AES256_GCM,data:9AyYZN9BAinSzEhDPjZL,iv:G5M3K2TI+qZKREl9tKfcI2EVHXrP88eQ5e7ryAQEXFk=,tag:jtlVuD7ZZMRfGZgVRzlMAg==,type:str]
type: ENC[AES256_GCM,data:7nekV5xU,iv:o07loB7RuYa7Yd5hrY6SKNWBIUSTcJJMU2Ej9IbI960=,tag:7VgRbVO7hNifII0sfp/A1w==,type:str]
stringData:
    BUGBARN_API_KEY: ENC[AES256_GCM,data:Iu+dywgxi+2PrNKN93ZVHb01IkjfJqQpPE5Aynxup061O38ci7YpYgdnQB7XqTfb,iv:VdF/3FL42c/Rz0Nd8dMGJAgiqTgcYTzba/3zDxj86oU=,tag:Fq1/bDMT6Ps+mjJLy0OxFw==,type:str]
    BUGBARN_ADMIN_USERNAME: ENC[AES256_GCM,data:0ftJA/o=,iv:uHbFmtVH0mUF3lsZgI+ldgdBe8JeiIhx4roIXLoF1o4=,tag:PygPHnqLgOqM5Oa+1vuV/Q==,type:str]
    BUGBARN_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:rG1NSU80PpX0zNsLP3vycOJTWfxf23RFlYtH+vu+a1XYjclVJVr4YV226u2j04UtYX8UgyU6FHAbed1G,iv:PZ+WbUTRJflpQSGuBan3EzbRX7TQk3WWoRkpkSNcNXA=,tag:mbTh8/9axNSIzty4/9LPhA==,type:str]
    BUGBARN_SESSION_SECRET: ENC[AES256_GCM,data:34UbytPL5g3/xC9fIat2aVOC3pRbM+6vhTnjseqABOo=,iv:eXLBNeKB/VcwWo0p00Tx861NujMMkIsSdsobcuGuLOk=,tag:O6k9LRMJxIK/hlMelglfUw==,type:str]
    BUGBARN_OIDC_ISSUER: ENC[AES256_GCM,data:wqbKyCfvzPcNXkOVVRUAluhcH3Rr0UbB4dc=,iv:5sXc4zq5Xdatnreo0/b8IpYTmZF7b34aoh5KQNSY3Ks=,tag:+Bx8Gz0iRPGHoiiXSIbWvg==,type:str]
    BUGBARN_OIDC_CLIENT_ID: ENC[AES256_GCM,data:KhNvbFWcBvC/bXhEnFVs3EXz,iv:tQ0XbIq3zo8iQiChWlj/DF+MaMhBChH1oUwKdJXz62o=,tag:vHXJQ4IvDCyPyfo+XcUJ8g==,type:str]
    BUGBARN_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:i1J+tI4fwBl7te4eJWolK3XVMN9RaCrRiZosPYWBSHQp0P2iG2CM2+3b0A==,iv:jm4wrYPf48RsN1kd9oZVDiquY1ejJWhTm+8nDuPP86U=,tag:Ft/AOK6JWEnwhPXBmCTUrw==,type:str]
    BUGBARN_OIDC_REDIRECT_URL: ENC[AES256_GCM,data:cc+Rue3nj0dcdDgsC3o2VRvWSQqwLg+zESSI0/MDy+10m0MmwdcnQGXa6lc98HmB1DAz,iv:DrP4CAp2Y0WXNM/sC2Nw1/mbGRW8k2lYatr6oTpVAMA=,tag:pf33R4ciqtjDd/5xq+Q8Ew==,type:str]
    BUGBARN_FUNNELBARN_ENDPOINT: ENC[AES256_GCM,data:RpWRk5bI9D162UZusFIf8/N6gevI4ZYqMpGGhmU0gyDm,iv:cIfzNtRqeCCjo+TFkgo785ZXPOEKyz3aYffRX0+dYaY=,tag:6+JF4DxK4rLIL5FN5rBMYg==,type:str]
    BUGBARN_FUNNELBARN_API_KEY: ENC[AES256_GCM,data:n/NNTFl2/e5sl0HSk9ItBmdDWpkfgBS+1B8x2pkgqLu224E9mRqVUQ==,iv:8jnPwDzxW6B5hKaISAZEaPyXQLnPfNY0NNjAXKER74E=,tag:85/XLCgYoXYVp/5P8kBqxw==,type:str]
    OTEL_EXPORTER_OTLP_ENDPOINT: ENC[AES256_GCM,data:8GtiOGOMW0Sh9m/RRGNwkXz5beQcrQe/+WNNlo1JHA==,iv:Uu9aTewJEoYMlCvXst96AP4pMj/cVSnhmbyuGAHvTYw=,tag:Qo6sEUapTbNMpF+emHntPQ==,type:str]
    OTEL_EXPORTER_OTLP_HEADERS: ENC[AES256_GCM,data:ADv3VGgylcZkYTDa1bLNVrsLvn9/iVrK3Bx5Qtgwt2q6aB4GPyfLa5jakOjUpzfotcW6m8e8yXNBj2+Lrg==,iv:Ptby5oDPKEslOD1mFLzHYw5L/pFASS/Ac4AUp4xYAKw=,tag:Dpt3ity/Rso+zZzuvDoJIA==,type:str]
sops:
    age:
        - recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOGJGY3pacVAyVEltSGhw
            VnRUUUJPSThvemhKQWErdTVmNTMrdXhPL2ljCndEYUR2UkhoOXVlVmNEMkZMdit0
            WHVFQllqam0yRk51Qkxac3dONWpKemcKLS0tIHJlUE15TU1WbVNRZW1qbzhNNklO
            TjRmTGMyN2FxOVVEUjdsSlRmb3BUc3MKtKPZO1Sc2ueHYsP9wELSdNdjSgR/9SWp
            rsEYda24zkgpiKdnE0lzytKojZCyIzz35rpmBSZ6TwUj7qXheyqDGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-16T12:03:25Z"
    mac: ENC[AES256_GCM,data:g+J6PcVjZMXJkDoEOpENp5hb60so7U1Wjz7SYd0dXyy4ukxA+zxOD5vb42Vo+jgOIp9+8cy4/3KfR+YuDLMGC9yC5jg+FSR6kCVDt2rZDVS/j7O4jnwTWjvXtCVbpphd4wSWBd9HF5CqlUAxK7CeGFElriaIUx4iZEllSxfOhOs=,iv:n+iPHj3cyI5h4NCL+O9qW4+e9tZF4L8IvMF8TAZ5pyI=,tag:qFlOocArhNDmZv0XQwViIg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
