apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugbarn-web
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bugbarn-web
      app.kubernetes.io/environment: testing
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bugbarn-web
        app.kubernetes.io/environment: testing
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s1
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: bugbarn-web
          image: bugbarn/web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: bugbarn-packages
              mountPath: /srv/packages
      volumes:
        - name: bugbarn-packages
          persistentVolumeClaim:
            claimName: bugbarn-packages
