stringData:
    api_key: ENC[AES256_GCM,data:MOZkLIm8fuolv7VXwUuP1AGRUeRJiGGqCVlNZH2acvFXJOzbi8yJZoyUD+AknmtaXgRrWyR7DVpGDGVqFHKTow==,iv:zED24Hf6rxjLd2pikjDJbhls6tPS2Of20mf01Gl9Ii0=,tag:nMnzF+KKFSi2TrQ2YBfuoA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMmRXSTlKbnorOWoya2px
            d281MXhXRGhTdXFDeHZUU080aGcrUnpwN2dJCnJjczkxNmtYaFhZUHV0aUttQVFT
            WE81MEFSQ3A0WEdnYVovRE1UYnBFUUUKLS0tIHJZYWk0bWdtRmcvUCs4WW9aY2xm
            Wk9taXRJeklVTW84emR3MGhDYk1JUjQKm9gpG3F/o7oD5rUTYMLieQAVedOXetXT
            65kZeq2SaJPIMKq2atBx7kYVRAJUO+w1cGZJELLAc7njNR79SXdyUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r7mrwf30q8g6glmngn2cnlzm9vrj6a9arz0t4mwxp6upc0m6tqwskvh295
    lastmodified: "2026-10-04T18:11:59Z"
    mac: ENC[AES256_GCM,data:tK7fXyIyy2ToFU8hY7TeAOZ9REm0PBp7uAKd/xhYvWAXihCW+rbQXkSLQYZ5qqzs3KA6sEBR3c12QQ3Y5DTMAXsVbPadBKNhmp0BxGiz0qlehaqIzQPOrR6BgpggIdpyv0eSoylkBl3W0m7L0Air1eSKDSWgdLQFSYXG4RDf6/s=,iv:/6p4cq4lO5/gFE4NQibw87u1dWQsTqDXSBNSPm0ka7M=,tag:ZurCohTJeK7cJswrqImAjw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
